# Generated by Django 3.2.9 on 2023-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_insertions',
            field=models.SmallIntegerField(default=0),
        ),
    ]
