# Generated by Django 4.0.3 on 2022-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_account',
            field=models.SmallIntegerField(choices=[(0, 'Customer'), (1, 'Farmer'), (2, 'Rider')], default=0),
        ),
    ]
