# Generated by Django 3.2.9 on 2023-04-02 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_user_number_insertions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_insertions',
        ),
        migrations.AddField(
            model_name='farmer',
            name='number_insertions',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmer',
            name='since',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 2, 16, 35, 14, 886945)),
        ),
    ]
