# Generated by Django 4.0.3 on 2022-07-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_user_type_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type_account',
            new_name='account_type',
        ),
    ]
