# Generated by Django 3.2.5 on 2022-10-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ext_farmer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_farmer', to='users_api.farmer'),
        ),
    ]
