# Generated by Django 3.2.5 on 2022-10-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_review_ext_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ext_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_api.farmer'),
        ),
    ]
