# Generated by Django 3.2.5 on 2022-09-15 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insertions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0), size=None), default=[], size=None),
        ),
    ]
