# Generated by Django 3.2.5 on 2023-04-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ext_farmer',
        ),
        migrations.AddField(
            model_name='review',
            name='ext_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default=None),
        ),
    ]
