# Generated by Django 4.0.3 on 2022-09-23 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_user_insertions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carts',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(default=0), size=None), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='insertions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0), size=None), default=list, size=None),
        ),
    ]
