# Generated by Django 3.2.5 on 2022-09-28 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0006_user_carts_alter_user_insertions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avalaible', models.BooleanField(default=False)),
                ('bio', models.CharField(max_length=255)),
                ('ext_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_user_r', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_location', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
                ('ext_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_user_f', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
