# Generated by Django 3.2.5 on 2022-09-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_auto_20220928_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='avalaible',
            field=models.CharField(max_length=255),
        ),
    ]
