# Generated by Django 3.2.5 on 2022-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0008_alter_rider_avalaible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='avalaible',
            field=models.BooleanField(default=b'I00\n'),
        ),
    ]
