# Generated by Django 4.0.3 on 2022-10-11 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0009_alter_rider_avalaible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='ext_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_user_f', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ext_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_user_r', to=settings.AUTH_USER_MODEL),
        ),
    ]
