# Generated by Django 3.2.5 on 2022-09-22 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='total_amount')),
                ('boxes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(default=0), size=None), default=list, size=None)),
            ],
        ),
    ]
