# Generated by Django 4.0.3 on 2022-09-23 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='boxes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
