# Generated by Django 3.2.5 on 2022-10-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='current_farmer',
            field=models.IntegerField(verbose_name='current_farmer'),
        ),
    ]
