# Generated by Django 3.2.9 on 2023-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='box_id',
            field=models.IntegerField(default=0),
        ),
    ]
