version: '3.3'

services:
  backend:
    build: .
    container_name: insertions_service_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: insertions_service_frontend
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  mongodb:
    image: mongo
    container_name: insertions_service_db
    ports:
      - 27017:27017
