version: '3.3'

services:
  backend:
    build: .
    container_name: insertions_service_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: insertions_service_db
    ports:
      - 27017:27017
