version: '3.3'

services:
  backend:
    build: .
    image: insertions_service_backend:v5
    container_name: insertions_service_backend
    command: sh -c "python3 wait_for_mongo.py insertions_service_db 27017 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  
  frontend:
    build: ./frontend
    image: insertions_service_frontend:v5
    container_name: insertions_service_frontend
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
      - backend
  
  mongodb:
    image: mongo
    container_name: insertions_service_db
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  # Optional
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
