# Generated by Django 3.2.9 on 2023-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.CharField(default=' ', max_length=150)),
                ('email', models.CharField(default=' ', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('box_names', models.CharField(default='', max_length=500)),
                ('farmer', models.IntegerField(default=-1)),
                ('rider', models.IntegerField(default=0)),
            ],
        ),
    ]
