# Generated by Django 3.2.5 on 2023-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.CharField(default=' ', max_length=150)),
                ('email', models.CharField(default=' ', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
            ],
        ),
    ]
