# Generated by Django 3.2.9 on 2023-03-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='tot_price',
        ),
    ]
