# Generated by Django 3.2.9 on 2023-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0003_rename_tot_price_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='box_names',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orders',
            name='farmer',
            field=models.IntegerField(default=-1),
        ),
    ]
