# Generated by Django 3.2.9 on 2023-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0004_auto_20230314_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rider',
            field=models.IntegerField(default=-1),
        ),
    ]
