# Generated by Django 3.2.5 on 2023-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0005_orders_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='rider',
            field=models.IntegerField(default=-2),
        ),
    ]
