# Generated by Django 3.2.5 on 2022-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertion',
            name='farmer',
            field=models.IntegerField(default=-1),
        ),
    ]
