# Generated by Django 3.2.9 on 2023-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
