# Generated by Django 3.2.9 on 2023-02-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_api', '0004_auto_20230225_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='insertions_api.user'),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='insertions_api.user'),
        ),
    ]
