# Generated by Django 3.2.9 on 2023-02-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_api', '0005_auto_20230225_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertion_farmer', to='insertions_api.user'),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insertion_user', to='insertions_api.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_farmer', to='insertions_api.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='insertions_api.user'),
        ),
    ]
