# Generated by Django 3.2.9 on 2023-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_api', '0006_auto_20230225_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
