# Generated by Django 3.2.9 on 2023-02-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_api', '0007_delete_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertion',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insertion_request', to='insertions_api.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='insertion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_insertion', to='insertions_api.insertion'),
        ),
    ]
