# Generated by Django 3.2.9 on 2023-02-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_api', '0008_auto_20230226_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertion',
            name='user',
        ),
    ]
