# Generated by Django 4.0.3 on 2022-04-04 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_address',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1977, 1, 1)),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.CharField(default=' ', max_length=60),
        ),
    ]
