# Generated by Django 4.0.3 on 2022-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='description',
            field=models.TextField(),
        ),
    ]
