# Generated by Django 4.0.3 on 2022-03-25 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0002_alter_insertion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertion',
            name='expiring_in',
        ),
        migrations.AddField(
            model_name='insertion',
            name='expiration_date',
            field=models.DateField(default=datetime.date(1977, 1, 1)),
        ),
    ]
