# Generated by Django 4.0.3 on 2022-03-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0008_insertion_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('insertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertions_manager.insertion')),
            ],
        ),
    ]
