# Generated by Django 4.0.3 on 2022-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0009_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='insertion',
            table='insertions',
        ),
    ]
