# Generated by Django 4.0.3 on 2022-03-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0010_alter_insertion_image_alter_insertion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insertion',
            table=None,
        ),
    ]
