# Generated by Django 4.0.3 on 2022-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0011_alter_insertion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='number_of_available_boxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
