# Generated by Django 4.0.3 on 2022-03-29 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0011_alter_insertion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='number_of_available_boxes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.PositiveIntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Big')], default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
