# Generated by Django 4.0.3 on 2022-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0012_box_number_of_available_boxes_alter_box_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
