# Generated by Django 4.0.3 on 2022-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0013_alter_insertion_description_alter_insertion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='gathering_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
