# Generated by Django 4.0.3 on 2022-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0014_alter_insertion_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.PositiveIntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Big')], default=0),
        ),
    ]
