# Generated by Django 4.0.3 on 2022-04-03 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions_manager', '0017_alter_box_number_of_available_boxes_alter_box_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='number_of_available_boxes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.PositiveIntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Big')], default=0),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
