# Generated by Django 3.1.13 on 2022-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('billing_address', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
