# Generated by Django 3.1.13 on 2022-09-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
